include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    lines_longer_than_80_chars: ignore
    avoid_catches_without_on_clauses: ignore
    one_member_abstracts: ignore
    flutter_style_todos: ignore
  exclude:
    - "**/*.g.dart"

linter:
  rules:
    sort_pub_dependencies: false
