include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    lines_longer_than_80_chars: ignore
  exclude:
    - "**/*.g.dart"

linter:
  rules:
    sort_pub_dependencies: false
